# CMake generated Testfile for 
# Source directory: /data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples
# Build directory: /data/lsl/SpGEMM/aocl-sparse-5.2.2/build-amd-gcc/tests/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[Sample.spmv_multi_instance]=] "sample_spmv_multi_instance")
set_tests_properties([=[Sample.spmv_multi_instance]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.zgthr]=] "sample_zgthr")
set_tests_properties([=[Sample.zgthr]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.zsp2m]=] "sample_zsp2m")
set_tests_properties([=[Sample.zsp2m]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.csr2m]=] "sample_csr2m")
set_tests_properties([=[Sample.csr2m]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dtrsv]=] "sample_dtrsv")
set_tests_properties([=[Sample.dtrsv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_d_cg_rci]=] "sample_itsol_d_cg_rci")
set_tests_properties([=[Sample.itsol_d_cg_rci]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_d_cg]=] "sample_itsol_d_cg")
set_tests_properties([=[Sample.itsol_d_cg]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_s_cg_rci]=] "sample_itsol_s_cg_rci")
set_tests_properties([=[Sample.itsol_s_cg_rci]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_s_cg]=] "sample_itsol_s_cg")
set_tests_properties([=[Sample.itsol_s_cg]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_d_gmres_rci]=] "sample_itsol_d_gmres_rci")
set_tests_properties([=[Sample.itsol_d_gmres_rci]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_d_gmres]=] "sample_itsol_d_gmres")
set_tests_properties([=[Sample.itsol_d_gmres]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_s_gmres_rci]=] "sample_itsol_s_gmres_rci")
set_tests_properties([=[Sample.itsol_s_gmres_rci]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_s_gmres]=] "sample_itsol_s_gmres")
set_tests_properties([=[Sample.itsol_s_gmres]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dsorv]=] "sample_dsorv")
set_tests_properties([=[Sample.dsorv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dotp]=] "sample_dotp")
set_tests_properties([=[Sample.dotp]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.sctr]=] "sample_sctr")
set_tests_properties([=[Sample.sctr]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.roti]=] "sample_roti")
set_tests_properties([=[Sample.roti]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dotmv]=] "sample_dotmv")
set_tests_properties([=[Sample.dotmv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.axpyi]=] "sample_axpyi")
set_tests_properties([=[Sample.axpyi]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.csrmm]=] "sample_csrmm")
set_tests_properties([=[Sample.csrmm]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dtrsm]=] "sample_dtrsm")
set_tests_properties([=[Sample.dtrsm]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.ztrsm]=] "sample_ztrsm")
set_tests_properties([=[Sample.ztrsm]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.spmv_c]=] "sample_spmv_c")
set_tests_properties([=[Sample.spmv_c]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.spmmd]=] "sample_spmmd")
set_tests_properties([=[Sample.spmmd]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dsyrk]=] "sample_dsyrk")
set_tests_properties([=[Sample.dsyrk]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.sp2md]=] "sample_sp2md")
set_tests_properties([=[Sample.sp2md]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.zsypr]=] "sample_zsypr")
set_tests_properties([=[Sample.zsypr]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dsyrkd]=] "sample_dsyrkd")
set_tests_properties([=[Sample.dsyrkd]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.syprd]=] "sample_syprd")
set_tests_properties([=[Sample.syprd]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dsymgs]=] "sample_dsymgs")
set_tests_properties([=[Sample.dsymgs]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.dsymgs_mv]=] "sample_dsymgs_mv")
set_tests_properties([=[Sample.dsymgs_mv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.zsymgs]=] "sample_zsymgs")
set_tests_properties([=[Sample.zsymgs]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.zsymgs_mv]=] "sample_zsymgs_mv")
set_tests_properties([=[Sample.zsymgs_mv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.tcsr_dspmv]=] "sample_tcsr_dspmv")
set_tests_properties([=[Sample.tcsr_dspmv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.tcsr_dtrsv]=] "sample_tcsr_dtrsv")
set_tests_properties([=[Sample.tcsr_dtrsv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.tcsr_ztrsv]=] "sample_tcsr_ztrsv")
set_tests_properties([=[Sample.tcsr_ztrsv]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_z_gmres_rci]=] "sample_itsol_z_gmres_rci")
set_tests_properties([=[Sample.itsol_z_gmres_rci]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.itsol_z_gmres]=] "sample_itsol_z_gmres")
set_tests_properties([=[Sample.itsol_z_gmres]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.mv_cpp]=] "sample_mv_cpp")
set_tests_properties([=[Sample.mv_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.trsv_cpp]=] "sample_trsv_cpp")
set_tests_properties([=[Sample.trsv_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
add_test([=[Sample.csr2m_cpp]=] "sample_csr2m_cpp")
set_tests_properties([=[Sample.csr2m_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;230;add_test;/data/lsl/SpGEMM/aocl-sparse-5.2.2/tests/examples/CMakeLists.txt;0;")
