# CMake generated Testfile for 
# Source directory: /data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test
# Build directory: /data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(batched_dla_serial "/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/KokkosKernels_batched_dla_serial")
set_tests_properties(batched_dla_serial PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/kokkos-kernels/cmake/fake_tribits.cmake;212;add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;194;kokkoskernels_add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;146;kokkoskernels_add_executable_and_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;99;kokkoskernels_add_unit_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;0;")
add_test(batched_gemm_serial "/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/KokkosKernels_batched_gemm_serial")
set_tests_properties(batched_gemm_serial PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/kokkos-kernels/cmake/fake_tribits.cmake;212;add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;194;kokkoskernels_add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;146;kokkoskernels_add_executable_and_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;104;kokkoskernels_add_unit_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;0;")
add_test(batched_dla_openmp "/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/KokkosKernels_batched_dla_openmp")
set_tests_properties(batched_dla_openmp PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/kokkos-kernels/cmake/fake_tribits.cmake;212;add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;194;kokkoskernels_add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;146;kokkoskernels_add_executable_and_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;111;kokkoskernels_add_unit_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;0;")
add_test(batched_gemm_openmp "/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/KokkosKernels_batched_gemm_openmp")
set_tests_properties(batched_gemm_openmp PROPERTIES  _BACKTRACE_TRIPLES "/data/lsl/SpGEMM/kokkos-kernels/cmake/fake_tribits.cmake;212;add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;194;kokkoskernels_add_test;/data/lsl/SpGEMM/kokkos-kernels/cmake/kokkoskernels_tribits.cmake;146;kokkoskernels_add_executable_and_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;116;kokkoskernels_add_unit_test;/data/lsl/SpGEMM/kokkos-kernels/batched/dense/unit_test/CMakeLists.txt;0;")
